# Generated by Django 2.2.6 on 2019-10-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_bugcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Complete', 'Complete')], default='New', max_length=11),
        ),
        migrations.DeleteModel(
            name='BugStatus',
        ),
    ]
