# Generated by Django 2.2.6 on 2019-10-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20191014_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='price',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='featurevotes',
            name='price',
            field=models.IntegerField(default=5),
        ),
    ]
