# Generated by Django 2.2.6 on 2019-10-16 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20191015_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='price',
            new_name='vote_price',
        ),
        migrations.DeleteModel(
            name='FeatureVotes',
        ),
    ]
